# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/BITCompare.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CompareBitError(object):
    def setupUi(self, CompareBitError):
        CompareBitError.setObjectName("CompareBitError")
        CompareBitError.resize(643, 963)
        self.treeView = QtWidgets.QTreeView(CompareBitError)
        self.treeView.setGeometry(QtCore.QRect(0, 250, 641, 701))
        self.treeView.setObjectName("treeView")
        self.groupBox = QtWidgets.QGroupBox(CompareBitError)
        self.groupBox.setGeometry(QtCore.QRect(200, 130, 120, 61))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 90, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 40, 90, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(CompareBitError)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 130, 120, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 20, 90, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 40, 90, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.groupBox_3 = QtWidgets.QGroupBox(CompareBitError)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 130, 120, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 20, 90, 16))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 40, 90, 16))
        self.radioButton_8.setObjectName("radioButton_8")
        self.lineEdit = QtWidgets.QLineEdit(CompareBitError)
        self.lineEdit.setGeometry(QtCore.QRect(0, 230, 641, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.progressBar = QtWidgets.QProgressBar(CompareBitError)
        self.progressBar.setGeometry(QtCore.QRect(0, 200, 641, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit_3 = QtWidgets.QLineEdit(CompareBitError)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 40, 491, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(CompareBitError)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 10, 491, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(CompareBitError)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 70, 121, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(CompareBitError)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 70, 491, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(CompareBitError)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 40, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(CompareBitError)
        self.pushButton.setGeometry(QtCore.QRect(520, 10, 121, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(CompareBitError)
        QtCore.QMetaObject.connectSlotsByName(CompareBitError)

    def retranslateUi(self, CompareBitError):
        _translate = QtCore.QCoreApplication.translate
        CompareBitError.setWindowTitle(_translate("CompareBitError", "GangImage Compare"))
        self.groupBox.setTitle(_translate("CompareBitError", "Page Size"))
        self.radioButton.setText(_translate("CompareBitError", "2048 Byte"))
        self.radioButton_2.setText(_translate("CompareBitError", "512 Byte"))
        self.groupBox_2.setTitle(_translate("CompareBitError", "Spare Area Size"))
        self.radioButton_3.setText(_translate("CompareBitError", "128 Byte"))
        self.radioButton_4.setText(_translate("CompareBitError", "64 Byte"))
        self.groupBox_3.setTitle(_translate("CompareBitError", "Erase Block Size"))
        self.radioButton_7.setText(_translate("CompareBitError", "128 Kb"))
        self.radioButton_8.setText(_translate("CompareBitError", "64 Kb"))
        self.pushButton_4.setText(_translate("CompareBitError", "Save AsFile"))
        self.pushButton_3.setText(_translate("CompareBitError", "Start"))
        self.pushButton_2.setText(_translate("CompareBitError", "Open Target"))
        self.pushButton.setText(_translate("CompareBitError", "Open Orgin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CompareBitError = QtWidgets.QDialog()
    ui = Ui_CompareBitError()
    ui.setupUi(CompareBitError)
    CompareBitError.show()
    sys.exit(app.exec_())
